apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: events-dep
spec: 
  replicas: 1 

  revisionHistoryLimit: 5
  strategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: "events"

  template: 
    metadata: 
      name: events 
      labels: 
        app: events 
        
    spec: 
      containers: 
        - image: eelcoh/poc.istio.events:0.0.1
          name: events
          ports: 
            - containerPort: 8080 
              protocol: TCP


