apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: messages-dep
spec: 
  replicas: 3 

  revisionHistoryLimit: 5
  strategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: "messages"

  template: 
    metadata: 
      name: messages 
      labels: 
        app: messages 
        
    spec: 
      containers: 
        - image: eelcoh/poc.istio.messages:0.0.1 
          name: messages
          ports: 
            - containerPort: 8080 
              protocol: TCP


