apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: tokens-dep
spec: 
  replicas: 3 

  revisionHistoryLimit: 5
  strategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: "tokens"

  template: 
    metadata: 
      name: tokens 
      labels: 
        app: tokens 
        
    spec: 
      containers: 
        - image: eelcoh/poc.istio.tokens:0.0.1 
          name: tokens
          ports: 
            - containerPort: 8080 
              protocol: TCP


